# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [4]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [6]:
print(A.shape)
print(A.ndim)
print(A.size)
print(A.dtype)

(3, 5)
2
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [7]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [8]:
print(B-C)
print()
print(B*C)
print()
print(B@C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [15]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
print(B)
print(np.exp(B))
print(B.min())  #all
print(B.min(1)) #row
print(B.min(0)) #col
print(np.argmin(B)) #first index (min v = 1 :: 0)
print(np.argmin(B,axis = 1,keepdims = True)) #första elementet i varje rad, ie 0,0 1,0 2,0
print(B.sum()) #summering, int
print(B.mean()) # 45 / 9 = 5, float
print(np.median(B))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[[0]
 [0]
 [0]]
45
5.0
5.0


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [54]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [55]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [57]:
# du får raden och alla element i raden, ie [0],[0] ; första raden och första elementet. [0] första raden
# [1] = andra raden
print(type(A[1])) # en array ; alla nummer i raden
print(type(A[1][1]))# int32 ; en int i arrayen [1]


<class 'numpy.ndarray'>
<class 'numpy.int32'>


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [58]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [75]:
for i in A:
    print(i)
    
print(A[0][1])
print(len(A))

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
2
3


In [90]:
for i in A:
    for j in range(len(A)):
        print(i[j]) #i = rad, index 0-2: j räknar från 0 till antal element i rad i "(len(A))"
        
print()
print(len(A[1])) #antal element i andra raden

        

1
2
3
6
7
8
11
12
13

5


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [91]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [122]:
print(type(a)) # är en array med bara en rad
#reshape ändrar dimensioner men inte datan

print(b) # 2st 3x5 matriser

c = np.arange(30)
d = c.reshape((-1, 3, 2)) # -1 betyder vad som än behövs men kan bara avändas en gång, 3 rader, 2 columnet ,-1 = 5 matriser
# 3 dimensionel matris
print()

print(d)

<class 'numpy.ndarray'>
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [123]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [124]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [125]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [5]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)
#tester
temp = 1
print(isinstance(A,np.ndarray))
print(isinstance(temp,np.ndarray))
print(A.shape)
print(A.shape[0])
print(C.shape)
print(E.shape)





[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]
True
False
(2, 3)
2
(2, 2)
(2, 1)


In [22]:
print(type(A))
print(isinstance(A,np.ndarray))
x = isinstance(A,np.ndarray) # returns false, x = false
print(x)# skiver false

if x == True:
    print("coolt")
else:
    print("inte coolt")
    
def temp123(a):
    """
    kolla om a och b är en ndarray/matris
    om inte, gör ej kalkulering
    """
    x = isinstance(a,np.ndarray)
    if x == False:
        return ("false")
    elif x == True:
        
        return (1+1)
            
print(temp123(2))  

<class 'numpy.ndarray'>
True
True
coolt
false


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [173]:
def add_mult_matrices(a,b,add_or_multiply):
    check_a = isinstance(a,np.ndarray)
    check_b = isinstance(b,np.ndarray)
    if check_a == False:
        return print("a is not a matrix")
    if check_b == False:
        return print("b is not a matrix")
    
    if add_or_multiply == "add":
        if a.shape == b.shape:
            return a+b
        else:
            return print("dimensions are not equal")
    elif add_or_multiply == "multiply":
        if a.shape[1] == b.shape[0]:
            return a@b
        else:
            return print("matrix a colums is not equal to matrix b rows")
        
print(A)
print(B)
print()
print(add_mult_matrices(A,B,"add"))
print()
print(add_mult_matrices(A,B,"multiply"))
print()
print(add_mult_matrices(C,E,"multiply"))
print()
# Compute if defined: B − 2A, 3C − E, AC, CD, CB.
print(add_mult_matrices(B,-A*2,"add"))
print()
print(add_mult_matrices(C*3,-E,"add"))
print()
print(add_mult_matrices(A,C,"multiply"))
print(A.shape,C.shape)
print()
print(add_mult_matrices(C,D,"multiply"))
print()
print(add_mult_matrices(C,B,"multiply"))


[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]

[[ 6 -1  0]
 [ 3 -5 -1]]

matrix a colums is not equal to matrix b rows
None

[[5]
 [4]]

[[ 0 -4  3]
 [ 0 -2 -4]]

dimensions are not equal
None

matrix a colums is not equal to matrix b rows
None
(2, 3) (2, 2)

[[11 10]
 [10 11]]

[[  8 -10  -3]
 [ 10  -8   0]]


**Chap2. Question 2**

In [184]:
A2 = np.array([[1, 2], [2, 4]])
B2 = np.array([[2, 1], [1, 3]])
C2 = np.array([[4, 3], [0, 2]])
print(A2)
print(B2)
print(C2)
ad2 = add_mult_matrices(A2,B2,"multiply")
ac2 = add_mult_matrices(A2,C2,"multiply")
print(ad2)
print("=")
print(ac2)
print()
print(B2, "=/=", C2)

[[1 2]
 [2 4]]
[[2 1]
 [1 3]]
[[4 3]
 [0 2]]
[[ 4  7]
 [ 8 14]]
=
[[ 4  7]
 [ 8 14]]

[[2 1]
 [1 3]] =/= [[4 3]
 [0 2]]


**Chap2. Question 3**

In [187]:
a23 = np.array([[1,1,1],[1,2,3],[1,3,4]])
d23 = np.array([[2,0,0],[0,3,0],[0,0,4]])
print(a23)
print()
print(d23)
print()
print(add_mult_matrices(a23,d23,"multiply"))
print()
print(add_mult_matrices(d23,a23,"multiply"))

[[1 1 1]
 [1 2 3]
 [1 3 4]]

[[2 0 0]
 [0 3 0]
 [0 0 4]]

[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [201]:
a112 = np.arange(1, 10).reshape(3,3)
print(a112)
print()
print(a112.transpose())
print()
print(add_mult_matrices(a112,a112.transpose(),"add"))
print()
print(add_mult_matrices(a112,a112.transpose(),"multiply"))
print()
print(add_mult_matrices(a112,-a112.transpose(),"add"))
print("^skewed symmetric")
print()
print(add_mult_matrices(a112.transpose(),a112,"multiply"))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]

[[ 0 -2 -4]
 [ 2  0 -2]
 [ 4  2  0]]
^skewed symmetric

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


**Chap 6. Question 1**

In [207]:
a61 = np.array([[5,6],[4,5]])
b61 = np.array([[6,4],[3,3]])
print(a61)
print(b61)
print()
print(np.linalg.inv(a61)) #scipy har liknande algo
print()
print(np.linalg.inv(b61))

[[5 6]
 [4 5]]
[[6 4]
 [3 3]]

[[ 5. -6.]
 [-4.  5.]]

[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [210]:
#obs page.19 quiz finnes ej, gjorde p.32 quiz question 3
q3 = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])
print(q3)
print()
print(np.linalg.inv(q3))
print("svar : d")

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


**Chap10. Question 1 a)**

In [220]:
print("3x1 − 7x2 − 2x3 = −7")
print("−3x1 + 5x2 + x3 = 5")
print("6x1 − 4x2 = 2")
a101a = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])
a101x = np.array([[-7],[5],[2]])
print(a101a)
print(a101x)
a101ax = np.concatenate((a101a,a101x),axis = 1) #lägger till andra matrisen vid columner, axis = 1 ; columner
print(a101ax) #behövdes tydligen inte men coolt
print()
svar10a=np.linalg.solve(a101a, a101x)
print(svar10a)
print()
print(np.allclose(np.dot(a101a, svar10a), a101x))#svar kontroll

3x1 − 7x2 − 2x3 = −7
−3x1 + 5x2 + x3 = 5
6x1 − 4x2 = 2
[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]
[[-7]
 [ 5]
 [ 2]]
[[ 3 -7 -2 -7]
 [-3  5  1  5]
 [ 6 -4  0  2]]

[[ 3.]
 [ 4.]
 [-6.]]

True


**Chap10. Question 1 b)**

In [221]:
b101a = np.array([[1,-2,3],[-1,3,-1],[2,-5,5]])
b101x = np.array([[1],[-1],[1]])

print(b101a)
print()
print(b101x)
print()
svar10b=np.linalg.solve(b101a, b101x)
print(svar10b)
print(np.allclose(np.dot(b101a, svar10b), b101x))#svar kontroll

[[ 1 -2  3]
 [-1  3 -1]
 [ 2 -5  5]]

[[ 1]
 [-1]
 [ 1]]

[[ 8.]
 [ 2.]
 [-1.]]
True


**Chap 12. Question 1**

In [222]:
a121 = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])
print(np.linalg.inv(a121))

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [223]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [224]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [225]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [ ]:
#v1 =  contiguous data buffer with the actual data elements
#v2 =  metadata that contains information about the data buffer. 
#The metadata includes data type, strides, and other important information that helps manipulate the ndarray easily
#basic indexin skapar en view inte en kopia
# i.e v2 = v1[-2:] gör v2 till en kopia då du indexar med [-2:]
# note, Advanced indexing, on the other hand, always creates copies. ex y = x[[1, 2]]